# .goreleaser.yml
project_name: git-profile
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
# Builds customization
builds:
  - id: default
    main: main.go
    binary: git-profile
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.CommitHash={{.Commit}} -X main.CompileDate={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
# Archives customization
archives:
  - id: default
    builds:
      - default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
# Homebrew customization
brews:
  - name: git-profile
    github:
      owner: dotzero
      name: homebrew-tap
    commit_author:
      name: dotzero
      email: mail@dotzero.ru
    folder: Formula
    homepage: https://github.com/dotzero/git-profile
    description: Allows switch between multiple user profiles in git repositories
    test: |
      system "#{bin}/git-profile version"
    install: |
      bin.install "git-profile"
