---
project_name: git-profile

archives:
  - id: git-profile
    files:
      - LICENSE*
      - README*
    format: tar.gz
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      386:    32bit
      amd64:  64bit
      darwin: macOS
      linux:  Linux

brews:
  - name: git-profile
    commit_author:
      name: dotzero
      email: mail@dotzero.ru
    description: Git Profile allows to add and switch between multiple user profiles in your git repositories
    folder: Formula
    homepage: https://github.com/dotzero/git-profile
    tap:
      owner: dotzero
      name:  homebrew-tap
    install: |
      bin.install "git-profile"
    test: |
      system "#{bin}/git-profile version"

builds:
  - binary: git-profile
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - 386
      - amd64
    goos:
      - darwin
      - linux
    ldflags: -s -w -X main.Version={{.Version}} -X main.CommitHash={{.Commit}} -X main.CompileDate={{.Date}}
    main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: dotzero
    name:  git-profile
