[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/matryer/is"
  version = "1.2.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"
